// priv/templates/daily_log.typ
// Daily Site Log — generated by SiteVoice AI

// ── Helpers ───────────────────────────────────────────────────────────────────
#let empty-val(v) = v == none or v == "nil" or v == ""
#let display(v, fallback: "—") = if empty-val(v) { fallback } else { v }
#let field(dict, key, fallback: "—") = display(dict.at(key, default: fallback), fallback: fallback)

#let to-num(v) = {
  if type(v) == str {
    if empty-val(v) { none } else { float(v) }
  } else if type(v) == float or type(v) == int { v }
  else { none }
}

// ── Palette ───────────────────────────────────────────────────────────────────
#let navy      = rgb("#0f2b46")
#let navy-mid  = rgb("#1e3a52")
#let orange    = rgb("#e8601c")
#let slate     = rgb("#64748b")
#let chalk     = rgb("#f8fafc")
#let green     = rgb("#166534")
#let green-bg  = rgb("#dcfce7")
#let amber     = rgb("#92400e")
#let amber-bg  = rgb("#fef3c7")
#let amber-brd = rgb("#d97706")
#let red       = rgb("#991b1b")
#let red-bg    = rgb("#fee2e2")
#let border    = rgb("#e2e8f0")
#let row-alt   = rgb("#f8fafc")

// ── Status badge ──────────────────────────────────────────────────────────────
#let status-badge(s) = {
  let cfg = if s == "submitted" { (green, green-bg, "SUBMITTED") }
    else if s == "draft"        { (amber, amber-bg, "DRAFT") }
    else if s == "processing"   { (slate, chalk, "PROCESSING") }
    else if s == "failed"       { (red, red-bg, "FAILED") }
    else                        { (slate, chalk, upper(s)) }
  let (fg, bg, label) = cfg
  box(
    fill: bg, stroke: 0.5pt + fg,
    inset: (x: 8pt, y: 4pt), radius: 3pt,
    text(size: 8pt, weight: "bold", fill: fg)[#label]
  )
}

// ── Section heading ───────────────────────────────────────────────────────────
#let section(title) = {
  v(1em)
  block(width: 100%, fill: navy, inset: (x: 9pt, y: 5pt), radius: 2pt)[
    #text(size: 8.5pt, weight: "bold", fill: white, tracking: 1pt)[#upper(title)]
  ]
  v(0.4em)
}

// ── Bullet row ────────────────────────────────────────────────────────────────
#let bullet-row(dot-color, body) = {
  grid(columns: (10pt, 1fr), gutter: 5pt,
    align(top)[#text(fill: dot-color, size: 11pt)[•]],
    block(inset: (top: 1pt))[#body]
  )
  v(0.25em)
}

// ── Page ──────────────────────────────────────────────────────────────────────
#set document(title: "Daily Log — " + elixir_data.date, date: datetime.today())
#set page(
  paper: "us-letter",
  margin: (x: 0.95in, y: 0.85in),
  footer: context [
    #line(length: 100%, stroke: 0.4pt + border)
    #v(3pt)
    #grid(columns: (1fr, auto),
      text(size: 7.5pt, fill: slate)[SiteVoice AI · PDF/A-3a · #elixir_data.log_id],
      text(size: 7.5pt, fill: slate)[Page #counter(page).display() of #counter(page).final().at(0)]
    )
  ]
)
#set text(font: "Barlow", size: 9.5pt, fill: rgb("#1e293b"))
#set par(leading: 0.65em)

// ── Header block ──────────────────────────────────────────────────────────────
#block(width: 100%, fill: navy, radius: 4pt, inset: (x: 18pt, y: 16pt))[
  #grid(columns: (1fr, auto), align: (left + top, right + top), gutter: 12pt,
    [
      #text(size: 7.5pt, fill: rgb("#7dd3fc"), weight: "bold", tracking: 3pt)[SITEVOICE]
      #v(5pt)
      #text(size: 22pt, weight: "bold", fill: white)[#elixir_data.project]
      #v(3pt)
      #text(size: 9pt, fill: rgb("#94a3b8"))[
        #elixir_data.organization
        #h(6pt)·#h(6pt)
        Code: #elixir_data.project_code
        #if not empty-val(elixir_data.project_address) [
          #h(6pt)·#h(6pt)
          #elixir_data.project_address
        ]
      ]
    ],
    [
      #status-badge(elixir_data.status)
      #v(10pt)
      #align(right)[
        #text(size: 8.5pt, fill: rgb("#cbd5e1"))[
          *#elixir_data.date* \
          #v(2pt)
          Foreman: #elixir_data.foreman \
          #v(2pt)
          Submitted: #elixir_data.submitted_at
        ]
      ]
    ]
  )
]

// ── Weather ───────────────────────────────────────────────────────────────────
#if not empty-val(elixir_data.weather) [
  #v(0.6em)
  #block(
    width: 100%, fill: chalk,
    stroke: (left: 3pt + orange), radius: 2pt,
    inset: (left: 12pt, right: 10pt, y: 7pt)
  )[
    #grid(columns: (auto, 1fr), gutter: 8pt, align: center + horizon,
      text(size: 11pt)[☀],
      text(size: 9pt)[*Weather* · #elixir_data.weather]
    )
  ]
]

// ── Labor ─────────────────────────────────────────────────────────────────────
#section("Labor")
#if elixir_data.labor.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No labor entries recorded.]
] else [
  #table(
    columns: (2fr, 1.5fr, 0.8fr, 0.8fr),
    stroke: (x, y) => if y == 0 { (bottom: 1pt + border) } else { none },
    fill: (x, y) => if y == 0 { chalk } else if calc.even(y) { white } else { row-alt },
    inset: (x: 8pt, y: 6pt),
    text(size: 8.5pt, weight: "bold")[Crew / Trade],
    text(size: 8.5pt, weight: "bold")[Classification],
    text(size: 8.5pt, weight: "bold")[Workers],
    text(size: 8.5pt, weight: "bold")[Hours],
    ..elixir_data.labor.map(e => (
      [#text(size: 9pt)[#field(e, "crew")]],
      [#text(size: 9pt, fill: slate)[#field(e, "trade")]],
      [#text(size: 9pt)[#field(e, "headcount")]],
      [#text(size: 9pt)[#field(e, "hours")]],
    )).flatten()
  )
]

// ── Progress ──────────────────────────────────────────────────────────────────
#section("Work Progress")
#if elixir_data.progress.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No progress entries recorded.]
] else [
  #for e in elixir_data.progress [
    #bullet-row(orange, [
      #field(e, "description")
      #let loc = e.at("location", default: "")
      #if not empty-val(loc) [
        #text(size: 8.5pt, fill: slate)[ — #loc]
      ]
    ])
  ]
]

// ── Equipment ─────────────────────────────────────────────────────────────────
#section("Equipment")
#if elixir_data.equipment.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No equipment entries recorded.]
] else [
  #for e in elixir_data.equipment [
    #bullet-row(slate, [
      *#field(e, "item")*
      #h(4pt)—#h(4pt)
      #field(e, "status")
      #let note = e.at("note", default: "")
      #if not empty-val(note) [
        #text(size: 8.5pt, fill: slate)[ · #note]
      ]
    ])
  ]
]

// ── Materials ─────────────────────────────────────────────────────────────────
#section("Materials Delivered")
#if elixir_data.materials.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No materials recorded.]
] else [
  #table(
    columns: (2fr, 1fr, 1.5fr),
    stroke: (x, y) => if y == 0 { (bottom: 1pt + border) } else { none },
    fill: (x, y) => if y == 0 { chalk } else if calc.even(y) { white } else { row-alt },
    inset: (x: 8pt, y: 6pt),
    text(size: 8.5pt, weight: "bold")[Item],
    text(size: 8.5pt, weight: "bold")[Quantity],
    text(size: 8.5pt, weight: "bold")[Received],
    ..elixir_data.materials.map(e => (
      [#text(size: 9pt)[#field(e, "item")]],
      [#text(size: 9pt)[#field(e, "quantity")]],
      [#text(size: 9pt, fill: slate)[#field(e, "received_at")]],
    )).flatten()
  )
]

// ── Delays ────────────────────────────────────────────────────────────────────
#section("Delays & Impacts")
#if elixir_data.delays.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No delays reported.]
] else [
  #for e in elixir_data.delays [
    #block(
      width: 100%, fill: amber-bg,
      stroke: (left: 3pt + amber-brd), radius: 2pt,
      inset: (left: 12pt, right: 10pt, y: 7pt)
    )[
      #text(size: 9pt)[#field(e, "description")]
      #let impact = e.at("impact", default: "")
      #if not empty-val(impact) [
        #linebreak()
        #text(size: 8.5pt, fill: amber)[Impact: #impact]
      ]
    ]
    #v(0.35em)
  ]
]

// ── Safety ────────────────────────────────────────────────────────────────────
#section("Safety Observations")
#if elixir_data.safety.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No safety entries recorded.]
] else [
  #for e in elixir_data.safety [
    #bullet-row(green, [
      #text(size: 9pt)[#field(e, "description")]
    ])
  ]
]

// ── Photos ────────────────────────────────────────────────────────────────────
#section("Site Photos")
#if elixir_data.photos.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No photos attached.]
] else [
  #grid(
    columns: 2,
    gutter: 10pt,
    ..elixir_data.photos.map(p => block(
      width: 100%,
      stroke: 0.5pt + border,
      radius: 3pt,
      inset: (x: 10pt, y: 8pt)
    )[
      #text(size: 8pt, weight: "bold", fill: orange)[#upper(field(p, "category", fallback: "Photo"))]
      #let cap = p.at("caption", default: "")
      #if not empty-val(cap) [
        #linebreak()
        #text(size: 8.5pt, fill: slate)[#cap]
      ]
    ])
  )
]

// ── Signature block ───────────────────────────────────────────────────────────
#v(1.5em)
#line(length: 100%, stroke: 0.5pt + border)
#v(0.6em)
#grid(
  columns: (1.8fr, 1fr, auto),
  gutter: 16pt,
  align: bottom,
  [
    #text(size: 8pt, fill: slate)[Foreman Signature]
    #v(18pt)
    #line(length: 90%, stroke: 0.5pt + rgb("#9ca3af"))
    #text(size: 8pt, fill: slate)[#elixir_data.foreman]
  ],
  [
    #text(size: 8pt, fill: slate)[Date]
    #v(18pt)
    #line(length: 80%, stroke: 0.5pt + rgb("#9ca3af"))
    #text(size: 8pt, fill: slate)[#elixir_data.submitted_at]
  ],
  [
    #let score = to-num(elixir_data.accuracy_score)
    #if score != none [
      #box(
        fill: green-bg, stroke: 0.5pt + green,
        inset: (x: 9pt, y: 5pt), radius: 3pt
      )[
        #text(size: 8pt, fill: green)[AI Accuracy: *#calc.round(score * 100, digits: 0)%*]
      ]
    ]
  ]
)
