// priv/templates/daily_log.typ
// Daily Site Log — generated by SiteVoice AI

// Numeric coercion: Elixir nil arrives as string "nil", floats arrive as strings
#let to-num(v) = {
  if type(v) == str {
    if v == "nil" or v == "" { none }
    else { float(v) }
  } else if type(v) == float or type(v) == int { v }
  else { none }
}

#let field(dict, key) = dict.at(key, default: "—")

#set document(title: "Daily Log — " + elixir_data.date, date: datetime.today())
#set page(paper: "us-letter", margin: (x: 1.2in, y: 1in))
#set text(font: "Barlow", size: 10pt)

// Header
#grid(columns: (1fr, auto), [
  = #elixir_data.project
  *Daily Site Log* — #elixir_data.date \
  Org: #elixir_data.organization · Code: #elixir_data.project_code
], [
  #align(right)[
    Foreman: *#elixir_data.foreman* \
    Submitted: #elixir_data.submitted_at
  ]
])

#line(length: 100%)

== Labor
#if elixir_data.labor.len() == 0 [
  _No labor entries._
] else [
  #for e in elixir_data.labor [
    - *#field(e, "crew")* (#field(e, "headcount") workers) — #field(e, "trade") | #field(e, "hours") hrs
  ]
]

== Progress
#if elixir_data.progress.len() == 0 [
  _No progress entries._
] else [
  #for e in elixir_data.progress [
    - #field(e, "description") #if "location" in e [ _(#e.location)_]
  ]
]

== Equipment
#if elixir_data.equipment.len() == 0 [
  _No equipment entries._
] else [
  #for e in elixir_data.equipment [
    - *#field(e, "item")* — #field(e, "status")#if "note" in e and e.at("note", default: "") != "" [ · #e.note]
  ]
]

== Materials
#if elixir_data.materials.len() == 0 [
  _No materials entries._
] else [
  #for e in elixir_data.materials [
    - #field(e, "item") × #field(e, "quantity") (received: #field(e, "received_at"))
  ]
]

== Delays
#if elixir_data.delays.len() == 0 [
  _No delays._
] else [
  #for e in elixir_data.delays [
    - #field(e, "description") — Impact: #field(e, "impact")
  ]
]

== Safety
#if elixir_data.safety.len() == 0 [
  _No safety entries._
] else [
  #for e in elixir_data.safety [
    - #field(e, "description")
  ]
]

== Photos
#if elixir_data.photos.len() == 0 [
  _No photos._
] else [
  #grid(columns: 3, gutter: 0.5em,
    ..elixir_data.photos.map(p => [
      #box(width: 100%)[
        #text(size: 8pt)[*#field(p, "category")* \ #field(p, "caption")]
      ]
    ])
  )
]

// Accuracy score (only shown when non-nil)
#let score = to-num(elixir_data.accuracy_score)
#if score != none [
  #v(0.5em)
  *AI Accuracy Score:* #calc.round(score * 100, digits: 0)%
]

#v(1fr)
#line(length: 100%, stroke: 0.5pt)
#text(size: 8pt, fill: gray)[SiteVoice AI · PDF/A-3a · #elixir_data.log_id]
