// priv/templates/weekly_report.typ
// Weekly Summary Report — generated by SiteVoice AI

// ── Helpers ───────────────────────────────────────────────────────────────────
#let empty-val(v) = v == none or v == "nil" or v == "" or v == "0" or v == 0
#let display(v, fallback: "—") = if empty-val(v) { fallback } else { v }
#let field(dict, key, fallback: "—") = display(dict.at(key, default: fallback), fallback: fallback)

#let to-num(v) = {
  if type(v) == str {
    if empty-val(v) { none } else { float(v) }
  } else if type(v) == float or type(v) == int { v }
  else { none }
}

// ── Palette ───────────────────────────────────────────────────────────────────
#let navy      = rgb("#0f2b46")
#let orange    = rgb("#e8601c")
#let slate     = rgb("#64748b")
#let chalk     = rgb("#f8fafc")
#let green     = rgb("#166534")
#let green-bg  = rgb("#dcfce7")
#let green-brd = rgb("#16a34a")
#let amber     = rgb("#92400e")
#let amber-bg  = rgb("#fef3c7")
#let amber-brd = rgb("#d97706")
#let red       = rgb("#991b1b")
#let red-bg    = rgb("#fee2e2")
#let red-brd   = rgb("#ef4444")
#let border    = rgb("#e2e8f0")
#let row-alt   = rgb("#f8fafc")

// ── Severity badge ────────────────────────────────────────────────────────────
#let severity-badge(s) = {
  let cfg = if s == "high"   { (red, red-bg) }
    else if s == "medium" { (amber, amber-bg) }
    else                  { (green, green-bg) }
  let (fg, bg) = cfg
  box(
    fill: bg, stroke: 0.5pt + fg,
    inset: (x: 6pt, y: 3pt), radius: 3pt,
    text(size: 7.5pt, weight: "bold", fill: fg)[#upper(s)]
  )
}

// ── Section heading ───────────────────────────────────────────────────────────
#let section(title) = {
  v(1em)
  block(width: 100%, fill: navy, inset: (x: 9pt, y: 5pt), radius: 2pt)[
    #text(size: 8.5pt, weight: "bold", fill: white, tracking: 1pt)[#upper(title)]
  ]
  v(0.4em)
}

// ── Stat cell ─────────────────────────────────────────────────────────────────
#let stat-cell(label, value) = {
  block(
    width: 100%,
    fill: chalk,
    stroke: 0.5pt + border,
    radius: 4pt,
    inset: (x: 12pt, y: 10pt)
  )[
    #text(size: 8pt, fill: slate, tracking: 0.5pt)[#upper(label)]
    #v(3pt)
    #text(size: 20pt, weight: "bold", fill: navy)[#value]
  ]
}

// ── Page ──────────────────────────────────────────────────────────────────────
#set document(
  title: "Weekly Report — " + elixir_data.project + " · " + elixir_data.week_start,
  date: datetime.today()
)
#set page(
  paper: "us-letter",
  margin: (x: 0.95in, y: 0.85in),
  footer: context [
    #set text(size: 7.5pt, fill: slate)
    #grid(
      columns: (1fr, auto),
      align(left)[SiteVoice AI · Weekly Report · #elixir_data.project],
      align(right)[Page #counter(page).display("1 of 1", both: true)]
    )
  ]
)
#set text(font: "Helvetica Neue", size: 10pt, fill: rgb("#1e293b"))
#set par(leading: 0.65em)

// ── Header ────────────────────────────────────────────────────────────────────
#block(
  width: 100%,
  fill: navy,
  radius: 5pt,
  inset: (x: 22pt, y: 18pt)
)[
  #grid(
    columns: (1fr, auto),
    align: horizon,
    [
      #text(size: 8pt, weight: "bold", fill: orange, tracking: 2pt)[SITEVOICE]
      #v(4pt)
      #text(size: 20pt, weight: "bold", fill: white)[Weekly Summary Report]
      #v(2pt)
      #text(size: 11pt, fill: rgb("#94a3b8"))[
        #elixir_data.project · #elixir_data.week_start – #elixir_data.week_end
      ]
    ],
    [
      #align(right)[
        #text(size: 8pt, fill: slate)[
          #elixir_data.organization \
          Generated #elixir_data.generated_at
        ]
      ]
    ]
  )
]

// ── Stats row ─────────────────────────────────────────────────────────────────
#v(0.8em)
#grid(
  columns: (1fr, 1fr, 1fr),
  gutter: 12pt,
  stat-cell("Days Logged", str(elixir_data.daily_log_count)),
  stat-cell("Total Hours", str(elixir_data.total_labor_hours)),
  stat-cell("Worker-Days", str(elixir_data.total_headcount_days))
)

// ── Executive Summary ─────────────────────────────────────────────────────────
#section("Executive Summary")
#if empty-val(elixir_data.summary) [
  #text(fill: slate, style: "italic", size: 9pt)[No summary available.]
] else [
  #text(size: 9.5pt, fill: rgb("#374151"))[#elixir_data.summary]
]

// ── Key Accomplishments ───────────────────────────────────────────────────────
#if elixir_data.key_accomplishments.len() > 0 [
  #section("Key Accomplishments")
  #block(
    width: 100%,
    fill: green-bg,
    stroke: (left: 3pt + green-brd),
    radius: 2pt,
    inset: (left: 12pt, right: 10pt, y: 10pt)
  )[
    #for item in elixir_data.key_accomplishments [
      #grid(
        columns: (10pt, 1fr),
        gutter: 5pt,
        align(top)[#text(fill: green, size: 11pt)[✓]],
        block(inset: (top: 1pt))[#text(size: 9pt)[#item]]
      )
      #v(0.3em)
    ]
  ]
]

// ── Outstanding Issues ────────────────────────────────────────────────────────
#if elixir_data.outstanding_issues.len() > 0 [
  #section("Outstanding Issues")
  #block(
    width: 100%,
    fill: red-bg,
    stroke: (left: 3pt + red-brd),
    radius: 2pt,
    inset: (left: 12pt, right: 10pt, y: 10pt)
  )[
    #for item in elixir_data.outstanding_issues [
      #grid(
        columns: (10pt, 1fr),
        gutter: 5pt,
        align(top)[#text(fill: red, size: 11pt)[!]],
        block(inset: (top: 1pt))[#text(size: 9pt)[#item]]
      )
      #v(0.3em)
    ]
  ]
]

// ── Trends ────────────────────────────────────────────────────────────────────
#if elixir_data.trends.len() > 0 [
  #section("Identified Trends")
  #for trend in elixir_data.trends [
    #let desc = field(trend, "description")
    #let sev  = trend.at("severity", default: "low")
    #grid(
      columns: (auto, 1fr),
      gutter: 8pt,
      align: top,
      severity-badge(sev),
      block(inset: (top: 2pt))[#text(size: 9pt)[#desc]]
    )
    #v(0.35em)
  ]
]

// ── Labor Summary ─────────────────────────────────────────────────────────────
#section("Labor Summary by Trade")
#if elixir_data.labor_by_trade.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No labor recorded this week.]
] else [
  #table(
    columns: (1fr, auto, auto),
    fill: (_, row) => if calc.odd(row) { row-alt } else { white },
    stroke: 0.5pt + border,
    inset: (x: 10pt, y: 7pt),
    table.header(
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[TRADE]],
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[WORKERS]],
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[HOURS]],
    ),
    ..elixir_data.labor_by_trade.map(e => (
      text(size: 9pt, weight: "bold")[#field(e, "trade")],
      align(center)[#text(size: 9pt)[#field(e, "total_headcount")]],
      align(center)[#text(size: 9pt)[#field(e, "total_hours")]],
    )).flatten()
  )
]

// ── Daily Snapshot ────────────────────────────────────────────────────────────
#section("Daily Activity Snapshot")
#if elixir_data.daily_snapshot.len() == 0 [
  #text(fill: slate, style: "italic", size: 9pt)[No daily logs this week.]
] else [
  #table(
    columns: (auto, 1fr, auto, auto),
    fill: (_, row) => if calc.odd(row) { row-alt } else { white },
    stroke: 0.5pt + border,
    inset: (x: 10pt, y: 7pt),
    table.header(
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[DATE]],
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[FOREMAN]],
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[WORKERS]],
      table.cell(fill: navy)[#text(size: 8pt, weight: "bold", fill: white, tracking: 0.5pt)[HOURS]],
    ),
    ..elixir_data.daily_snapshot.map(e => (
      text(size: 9pt, fill: slate)[#field(e, "date")],
      text(size: 9pt)[#field(e, "foreman")],
      align(center)[#text(size: 9pt)[#field(e, "headcount")]],
      align(center)[#text(size: 9pt)[#field(e, "hours")]],
    )).flatten()
  )
]

// ── Weather ───────────────────────────────────────────────────────────────────
#if not empty-val(elixir_data.weather) [
  #v(0.5em)
  #block(
    width: 100%,
    fill: chalk,
    stroke: 0.5pt + border,
    radius: 3pt,
    inset: (x: 12pt, y: 9pt)
  )[
    #text(size: 8pt, weight: "bold", fill: slate, tracking: 0.5pt)[WEATHER CONDITIONS: ]
    #text(size: 9pt)[#elixir_data.weather]
  ]
]

// ── Footer line ───────────────────────────────────────────────────────────────
#v(1.5em)
#line(length: 100%, stroke: 0.5pt + border)
#v(0.4em)
#text(size: 7.5pt, fill: slate)[Generated by SiteVoice AI · Confidential — For internal use only]
