defmodule Sitevoice.Repo.Migrations.AddClarificationToDailyLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:daily_logs) do
      add :clarification_questions, {:array, :map}, default: []
      add :clarification_audio_key, :text
      add :clarification_audio_duration, :bigint
      add :clarification_transcript, :text
      add :clarification_round, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:daily_logs) do
      remove :clarification_round
      remove :clarification_transcript
      remove :clarification_audio_duration
      remove :clarification_audio_key
      remove :clarification_questions
    end
  end
end
