defmodule Sitevoice.Repo.Migrations.AuthUserTenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :organization_id, :uuid, null: false

      add :version_source_id,
          references(:users,
            column: :id,
            name: "users_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:users) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "users_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :role, :text, null: false, default: "foreman"
      add :preferred_language, :text, default: "en"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:users, [:organization_id, :role])

    create index(:users, [:organization_id, :email], unique: true)

    create index(:users, [:organization_id])

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    create unique_index(:users, [:organization_id, :email], name: "users_unique_email_index")

    create unique_index(:users, [:organization_id, :email],
             name: "users_unique_email_per_org_index"
           )

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:users, "users_organization_id_fkey")

    drop_if_exists unique_index(:users, [:organization_id, :email],
                     name: "users_unique_email_per_org_index"
                   )

    drop_if_exists unique_index(:users, [:organization_id, :email],
                     name: "users_unique_email_index"
                   )

    create unique_index(:users, [:email], name: "users_unique_email_index")

    drop_if_exists index(:users, [:organization_id])

    drop_if_exists index(:users, [:organization_id, :email])

    drop_if_exists index(:users, [:organization_id, :role])

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :preferred_language
      remove :role
      remove :name
      remove :organization_id
    end

    drop constraint(:users_versions, "users_versions_version_source_id_fkey")

    drop table(:users_versions)
  end
end
