defmodule Sitevoice.Repo.Migrations.AddDailyLogBriefToProjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:projects) do
      add :required_sections, {:array, :text}, default: ["labor", "progress", "safety"]

      add :daily_log_context, :text,
        default:
          "General construction site. Each daily log should describe crew composition by trade, the day's work progress with locations, any safety incidents (or 'none'), notable deliveries or equipment movements, and any delays. Note weather if it affected work."

      add :daily_log_min_accuracy, :float, default: 0.7
    end
  end

  def down do
    alter table(:projects) do
      remove :daily_log_min_accuracy
      remove :daily_log_context
      remove :required_sections
    end
  end
end
