defmodule Sitevoice.Repo.Migrations.AddOrgIdToVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:daily_logs_versions) do
      add :organization_id, :uuid, null: false
    end
  end

  def down do
    alter table(:daily_logs_versions) do
      remove :organization_id
    end
  end
end
