defmodule Sitevoice.Repo.Migrations.CrewRosterAttendance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:daily_attendances, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "daily_attendances_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :headcount_present, :bigint, null: false, default: 0
      add :headcount_absent, :bigint, null: false, default: 0
      add :hours, :float, null: false, default: 8.0
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :daily_log_id,
          references(:daily_logs,
            column: :id,
            name: "daily_attendances_daily_log_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :crew_template_id, :uuid, null: false
    end

    create index(:daily_attendances, [:organization_id, :daily_log_id],
             name: "daily_attendances_org_log_idx"
           )

    create unique_index(:daily_attendances, [:organization_id, :daily_log_id, :crew_template_id],
             name: "daily_attendances_unique_log_crew_index"
           )

    create table(:crew_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:daily_attendances) do
      modify :crew_template_id,
             references(:crew_templates,
               column: :id,
               name: "daily_attendances_crew_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:crew_templates) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "crew_templates_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :trade, :text, default: "general"
      add :subcontractor, :text
      add :default_headcount, :bigint, null: false, default: 1
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "crew_templates_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:crew_templates, [:organization_id, :project_id],
             name: "crew_templates_org_project_idx"
           )
  end

  def down do
    drop constraint(:crew_templates, "crew_templates_organization_id_fkey")

    drop constraint(:crew_templates, "crew_templates_project_id_fkey")

    drop_if_exists index(:crew_templates, [:organization_id, :project_id],
                     name: "crew_templates_org_project_idx"
                   )

    alter table(:crew_templates) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :default_headcount
      remove :subcontractor
      remove :trade
      remove :name
      remove :organization_id
    end

    drop constraint(:daily_attendances, "daily_attendances_crew_template_id_fkey")

    alter table(:daily_attendances) do
      modify :crew_template_id, :uuid
    end

    drop table(:crew_templates)

    drop constraint(:daily_attendances, "daily_attendances_organization_id_fkey")

    drop constraint(:daily_attendances, "daily_attendances_daily_log_id_fkey")

    drop_if_exists unique_index(
                     :daily_attendances,
                     [:organization_id, :daily_log_id, :crew_template_id],
                     name: "daily_attendances_unique_log_crew_index"
                   )

    drop_if_exists index(:daily_attendances, [:organization_id, :daily_log_id],
                     name: "daily_attendances_org_log_idx"
                   )

    drop table(:daily_attendances)
  end
end
