defmodule Sitevoice.Repo.Migrations.WeeklyReport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:weekly_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "weekly_reports_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :week_start, :date, null: false
      add :week_end, :date, null: false
      add :status, :text, null: false, default: "pending"
      add :summary, :text
      add :key_accomplishments, {:array, :text}, default: []
      add :outstanding_issues, {:array, :text}, default: []
      add :trends, {:array, :map}, default: []
      add :total_labor_hours, :float
      add :total_headcount_days, :bigint
      add :daily_log_count, :bigint
      add :pdf_key, :text
      add :generated_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "weekly_reports_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:weekly_reports, [:organization_id, :project_id, :week_start],
             name: "weekly_reports_org_project_week_idx"
           )

    create unique_index(:weekly_reports, [:organization_id, :project_id, :week_start],
             name: "weekly_reports_unique_report_per_week_index"
           )
  end

  def down do
    drop constraint(:weekly_reports, "weekly_reports_organization_id_fkey")

    drop constraint(:weekly_reports, "weekly_reports_project_id_fkey")

    drop_if_exists unique_index(:weekly_reports, [:organization_id, :project_id, :week_start],
                     name: "weekly_reports_unique_report_per_week_index"
                   )

    drop_if_exists index(:weekly_reports, [:organization_id, :project_id, :week_start],
                     name: "weekly_reports_org_project_week_idx"
                   )

    drop table(:weekly_reports)
  end
end
