defmodule Sitevoice.Repo.Migrations.ProjectsResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:users_versions, "users_versions_version_source_id_fkey")

    alter table(:users_versions) do
      modify :version_source_id,
             references(:users,
               column: :id,
               name: "users_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create table(:projects_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :organization_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:projects_versions) do
      modify :version_source_id,
             references(:projects,
               column: :id,
               name: "projects_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:projects) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "projects_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :name, :text, null: false
      add :code, :text, null: false
      add :address, :text
      add :timezone, :text, default: "America/Phoenix"
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:projects, [:organization_id, :active])

    create index(:projects, [:organization_id, :code], unique: true)

    create index(:projects, [:organization_id])

    create unique_index(:projects, [:organization_id, :code],
             name: "projects_unique_code_per_org_index"
           )

    create table(:project_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "project_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "project_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_memberships_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:project_memberships, [:organization_id, :project_id])

    create index(:project_memberships, [:organization_id, :user_id])

    create index(:project_memberships, [:organization_id, :project_id, :user_id], unique: true)

    create unique_index(:project_memberships, [:organization_id, :project_id, :user_id],
             name: "project_memberships_unique_membership_index"
           )

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:project_memberships, "project_memberships_organization_id_fkey")

    drop constraint(:project_memberships, "project_memberships_user_id_fkey")

    drop constraint(:project_memberships, "project_memberships_project_id_fkey")

    drop_if_exists unique_index(:project_memberships, [:organization_id, :project_id, :user_id],
                     name: "project_memberships_unique_membership_index"
                   )

    drop_if_exists index(:project_memberships, [:organization_id, :project_id, :user_id])

    drop_if_exists index(:project_memberships, [:organization_id, :user_id])

    drop_if_exists index(:project_memberships, [:organization_id, :project_id])

    drop table(:project_memberships)

    drop constraint(:projects, "projects_organization_id_fkey")

    drop_if_exists unique_index(:projects, [:organization_id, :code],
                     name: "projects_unique_code_per_org_index"
                   )

    drop_if_exists index(:projects, [:organization_id])

    drop_if_exists index(:projects, [:organization_id, :code])

    drop_if_exists index(:projects, [:organization_id, :active])

    alter table(:projects) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :timezone
      remove :address
      remove :code
      remove :name
      remove :organization_id
    end

    drop constraint(:projects_versions, "projects_versions_version_source_id_fkey")

    alter table(:projects_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:projects)

    drop table(:projects_versions)

    drop constraint(:users_versions, "users_versions_version_source_id_fkey")

    alter table(:users_versions) do
      modify :version_source_id,
             references(:users,
               column: :id,
               name: "users_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
