defmodule Sitevoice.Repo.Migrations.IncrementalLogEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:log_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "log_entries_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :type, :text, null: false
      add :audio_key, :text
      add :audio_duration, :bigint
      add :transcript, :text
      add :text, :text
      add :photo_key, :text
      add :caption, :text
      add :captured_at, :utc_datetime_usec, null: false
      add :sort_order, :bigint, default: 0
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :daily_log_id,
          references(:daily_logs,
            column: :id,
            name: "log_entries_daily_log_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:log_entries, [:organization_id, :daily_log_id, :captured_at],
             name: "log_entries_org_log_captured_idx"
           )
  end

  def down do
    drop constraint(:log_entries, "log_entries_organization_id_fkey")

    drop constraint(:log_entries, "log_entries_daily_log_id_fkey")

    drop_if_exists index(:log_entries, [:organization_id, :daily_log_id, :captured_at],
                     name: "log_entries_org_log_captured_idx"
                   )

    drop table(:log_entries)
  end
end
