defmodule Sitevoice.Repo.Migrations.AddCorrectionsToDailyLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:daily_logs) do
      add :corrections, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:daily_logs) do
      remove :corrections
    end
  end
end
