defmodule Sitevoice.Repo.Migrations.AddActiveInvitedAtToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :active, :boolean, null: false, default: true
      add :invited_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :invited_at
      remove :active
    end
  end
end
