defmodule Sitevoice.Repo.Migrations.RecordingResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:photos, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "photos_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :storage_key, :text, null: false
      add :caption, :text
      add :category, :text
      add :taken_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :daily_log_id, :uuid, null: false
    end

    create index(:photos, [:organization_id, :daily_log_id])

    create table(:daily_logs_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:daily_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:photos) do
      modify :daily_log_id,
             references(:daily_logs,
               column: :id,
               name: "photos_daily_log_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:daily_logs_versions) do
      modify :version_source_id,
             references(:daily_logs,
               column: :id,
               name: "daily_logs_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:daily_logs) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "daily_logs_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :date, :date, null: false
      add :status, :text, null: false, default: "pending"
      add :audio_key, :text
      add :audio_duration, :bigint
      add :transcript, :text
      add :accuracy_score, :float
      add :labor, {:array, :map}, default: []
      add :progress, {:array, :map}, default: []
      add :equipment, {:array, :map}, default: []
      add :materials, {:array, :map}, default: []
      add :delays, {:array, :map}, default: []
      add :safety, {:array, :map}, default: []
      add :pdf_key, :text
      add :weather, :text
      add :submitted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :foreman_id,
          references(:users,
            column: :id,
            name: "daily_logs_foreman_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :project_id,
          references(:projects,
            column: :id,
            name: "daily_logs_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end

    create index(:daily_logs, [:organization_id, :project_id, :status],
             name: "daily_logs_org_project_status_idx"
           )

    create index(:daily_logs, [:organization_id, :status], name: "daily_logs_org_status_idx")

    create index(:daily_logs, [:organization_id, :foreman_id, :date],
             name: "daily_logs_org_foreman_date_idx"
           )

    create index(:daily_logs, [:organization_id, :project_id, :date],
             name: "daily_logs_org_project_date_idx"
           )

    create unique_index(:daily_logs, [:organization_id, :date, :foreman_id, :project_id],
             name: "daily_logs_unique_log_per_day_index"
           )
  end

  def down do
    drop constraint(:daily_logs, "daily_logs_organization_id_fkey")

    drop constraint(:daily_logs, "daily_logs_foreman_id_fkey")

    drop constraint(:daily_logs, "daily_logs_project_id_fkey")

    drop_if_exists unique_index(:daily_logs, [:organization_id, :date, :foreman_id, :project_id],
                     name: "daily_logs_unique_log_per_day_index"
                   )

    drop_if_exists index(:daily_logs, [:organization_id, :project_id, :date],
                     name: "daily_logs_org_project_date_idx"
                   )

    drop_if_exists index(:daily_logs, [:organization_id, :foreman_id, :date],
                     name: "daily_logs_org_foreman_date_idx"
                   )

    drop_if_exists index(:daily_logs, [:organization_id, :status],
                     name: "daily_logs_org_status_idx"
                   )

    drop_if_exists index(:daily_logs, [:organization_id, :project_id, :status],
                     name: "daily_logs_org_project_status_idx"
                   )

    alter table(:daily_logs) do
      remove :project_id
      remove :foreman_id
      remove :updated_at
      remove :inserted_at
      remove :submitted_at
      remove :weather
      remove :pdf_key
      remove :safety
      remove :delays
      remove :materials
      remove :equipment
      remove :progress
      remove :labor
      remove :accuracy_score
      remove :transcript
      remove :audio_duration
      remove :audio_key
      remove :status
      remove :date
      remove :organization_id
    end

    drop constraint(:daily_logs_versions, "daily_logs_versions_version_source_id_fkey")

    alter table(:daily_logs_versions) do
      modify :version_source_id, :uuid
    end

    drop constraint(:photos, "photos_daily_log_id_fkey")

    alter table(:photos) do
      modify :daily_log_id, :uuid
    end

    drop table(:daily_logs)

    drop table(:daily_logs_versions)

    drop constraint(:photos, "photos_organization_id_fkey")

    drop_if_exists index(:photos, [:organization_id, :daily_log_id])

    drop table(:photos)
  end
end
